[package]
name = "analysis"
edition.workspace = true
version.workspace = true
publish.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
ipnetwork.workspace = true
maxminddb.workspace = true
model.workspace = true
src-atlas.workspace = true
src-geofeed.workspace = true

[dev-dependencies]
ipnet.workspace = true
mmdb-writer.workspace = true
