[package]
name = "pipeline"
edition.workspace = true
version.workspace = true
publish.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
analysis.workspace = true
anyhow.workspace = true
csv.workspace = true
fetch.workspace = true
flate2.workspace = true
ipnet.workspace = true
maxminddb.workspace = true
merge.workspace = true
mmdb-writer.workspace = true
model.workspace = true
serde.workspace = true
serde_json.workspace = true
src-arin.workspace = true
src-aspop.workspace = true
src-asnames.workspace = true
src-atlas.workspace = true
src-bgp.workspace = true
src-delegated.workspace = true
src-geofeed.workspace = true
src-peeringdb.workspace = true
src-rpki.workspace = true
src-rpsl.workspace = true
