[package]
name = "src-bgp"
edition.workspace = true
version.workspace = true
publish.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
bgpkit-parser.workspace = true
flate2.workspace = true
ipnet.workspace = true
model.workspace = true
