#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum Continent {
    Africa,
    Antarctica,
    Asia,
    Europe,
    NorthAmerica,
    Oceania,
    SouthAmerica,
}

impl Continent {
    pub const ALL: [Continent; 7] = [
        Continent::Africa,
        Continent::Antarctica,
        Continent::Asia,
        Continent::Europe,
        Continent::NorthAmerica,
        Continent::Oceania,
        Continent::SouthAmerica,
    ];

    pub fn code(self) -> &'static str {
        match self {
            Continent::Africa => "AF",
            Continent::Antarctica => "AN",
            Continent::Asia => "AS",
            Continent::Europe => "EU",
            Continent::NorthAmerica => "NA",
            Continent::Oceania => "OC",
            Continent::SouthAmerica => "SA",
        }
    }

    pub fn name(self) -> &'static str {
        match self {
            Continent::Africa => "Africa",
            Continent::Antarctica => "Antarctica",
            Continent::Asia => "Asia",
            Continent::Europe => "Europe",
            Continent::NorthAmerica => "North America",
            Continent::Oceania => "Oceania",
            Continent::SouthAmerica => "South America",
        }
    }
}

const COUNTRIES: [(&str, Continent); 249] = [
    ("AD", Continent::Europe),
    ("AE", Continent::Asia),
    ("AF", Continent::Asia),
    ("AG", Continent::NorthAmerica),
    ("AI", Continent::NorthAmerica),
    ("AL", Continent::Europe),
    ("AM", Continent::Asia),
    ("AO", Continent::Africa),
    ("AQ", Continent::Antarctica),
    ("AR", Continent::SouthAmerica),
    ("AS", Continent::Oceania),
    ("AT", Continent::Europe),
    ("AU", Continent::Oceania),
    ("AW", Continent::NorthAmerica),
    ("AX", Continent::Europe),
    ("AZ", Continent::Asia),
    ("BA", Continent::Europe),
    ("BB", Continent::NorthAmerica),
    ("BD", Continent::Asia),
    ("BE", Continent::Europe),
    ("BF", Continent::Africa),
    ("BG", Continent::Europe),
    ("BH", Continent::Asia),
    ("BI", Continent::Africa),
    ("BJ", Continent::Africa),
    ("BL", Continent::NorthAmerica),
    ("BM", Continent::NorthAmerica),
    ("BN", Continent::Asia),
    ("BO", Continent::SouthAmerica),
    ("BQ", Continent::NorthAmerica),
    ("BR", Continent::SouthAmerica),
    ("BS", Continent::NorthAmerica),
    ("BT", Continent::Asia),
    ("BV", Continent::Antarctica),
    ("BW", Continent::Africa),
    ("BY", Continent::Europe),
    ("BZ", Continent::NorthAmerica),
    ("CA", Continent::NorthAmerica),
    ("CC", Continent::Asia),
    ("CD", Continent::Africa),
    ("CF", Continent::Africa),
    ("CG", Continent::Africa),
    ("CH", Continent::Europe),
    ("CI", Continent::Africa),
    ("CK", Continent::Oceania),
    ("CL", Continent::SouthAmerica),
    ("CM", Continent::Africa),
    ("CN", Continent::Asia),
    ("CO", Continent::SouthAmerica),
    ("CR", Continent::NorthAmerica),
    ("CU", Continent::NorthAmerica),
    ("CV", Continent::Africa),
    ("CW", Continent::NorthAmerica),
    ("CX", Continent::Oceania),
    ("CY", Continent::Europe),
    ("CZ", Continent::Europe),
    ("DE", Continent::Europe),
    ("DJ", Continent::Africa),
    ("DK", Continent::Europe),
    ("DM", Continent::NorthAmerica),
    ("DO", Continent::NorthAmerica),
    ("DZ", Continent::Africa),
    ("EC", Continent::SouthAmerica),
    ("EE", Continent::Europe),
    ("EG", Continent::Africa),
    ("EH", Continent::Africa),
    ("ER", Continent::Africa),
    ("ES", Continent::Europe),
    ("ET", Continent::Africa),
    ("FI", Continent::Europe),
    ("FJ", Continent::Oceania),
    ("FK", Continent::SouthAmerica),
    ("FM", Continent::Oceania),
    ("FO", Continent::Europe),
    ("FR", Continent::Europe),
    ("GA", Continent::Africa),
    ("GB", Continent::Europe),
    ("GD", Continent::NorthAmerica),
    ("GE", Continent::Asia),
    ("GF", Continent::SouthAmerica),
    ("GG", Continent::Europe),
    ("GH", Continent::Africa),
    ("GI", Continent::Europe),
    ("GL", Continent::NorthAmerica),
    ("GM", Continent::Africa),
    ("GN", Continent::Africa),
    ("GP", Continent::NorthAmerica),
    ("GQ", Continent::Africa),
    ("GR", Continent::Europe),
    ("GS", Continent::Antarctica),
    ("GT", Continent::NorthAmerica),
    ("GU", Continent::Oceania),
    ("GW", Continent::Africa),
    ("GY", Continent::SouthAmerica),
    ("HK", Continent::Asia),
    ("HM", Continent::Antarctica),
    ("HN", Continent::NorthAmerica),
    ("HR", Continent::Europe),
    ("HT", Continent::NorthAmerica),
    ("HU", Continent::Europe),
    ("ID", Continent::Asia),
    ("IE", Continent::Europe),
    ("IL", Continent::Asia),
    ("IM", Continent::Europe),
    ("IN", Continent::Asia),
    ("IO", Continent::Asia),
    ("IQ", Continent::Asia),
    ("IR", Continent::Asia),
    ("IS", Continent::Europe),
    ("IT", Continent::Europe),
    ("JE", Continent::Europe),
    ("JM", Continent::NorthAmerica),
    ("JO", Continent::Asia),
    ("JP", Continent::Asia),
    ("KE", Continent::Africa),
    ("KG", Continent::Asia),
    ("KH", Continent::Asia),
    ("KI", Continent::Oceania),
    ("KM", Continent::Africa),
    ("KN", Continent::NorthAmerica),
    ("KP", Continent::Asia),
    ("KR", Continent::Asia),
    ("KW", Continent::Asia),
    ("KY", Continent::NorthAmerica),
    ("KZ", Continent::Asia),
    ("LA", Continent::Asia),
    ("LB", Continent::Asia),
    ("LC", Continent::NorthAmerica),
    ("LI", Continent::Europe),
    ("LK", Continent::Asia),
    ("LR", Continent::Africa),
    ("LS", Continent::Africa),
    ("LT", Continent::Europe),
    ("LU", Continent::Europe),
    ("LV", Continent::Europe),
    ("LY", Continent::Africa),
    ("MA", Continent::Africa),
    ("MC", Continent::Europe),
    ("MD", Continent::Europe),
    ("ME", Continent::Europe),
    ("MF", Continent::NorthAmerica),
    ("MG", Continent::Africa),
    ("MH", Continent::Oceania),
    ("MK", Continent::Europe),
    ("ML", Continent::Africa),
    ("MM", Continent::Asia),
    ("MN", Continent::Asia),
    ("MO", Continent::Asia),
    ("MP", Continent::Oceania),
    ("MQ", Continent::NorthAmerica),
    ("MR", Continent::Africa),
    ("MS", Continent::NorthAmerica),
    ("MT", Continent::Europe),
    ("MU", Continent::Africa),
    ("MV", Continent::Asia),
    ("MW", Continent::Africa),
    ("MX", Continent::NorthAmerica),
    ("MY", Continent::Asia),
    ("MZ", Continent::Africa),
    ("NA", Continent::Africa),
    ("NC", Continent::Oceania),
    ("NE", Continent::Africa),
    ("NF", Continent::Oceania),
    ("NG", Continent::Africa),
    ("NI", Continent::NorthAmerica),
    ("NL", Continent::Europe),
    ("NO", Continent::Europe),
    ("NP", Continent::Asia),
    ("NR", Continent::Oceania),
    ("NU", Continent::Oceania),
    ("NZ", Continent::Oceania),
    ("OM", Continent::Asia),
    ("PA", Continent::NorthAmerica),
    ("PE", Continent::SouthAmerica),
    ("PF", Continent::Oceania),
    ("PG", Continent::Oceania),
    ("PH", Continent::Asia),
    ("PK", Continent::Asia),
    ("PL", Continent::Europe),
    ("PM", Continent::NorthAmerica),
    ("PN", Continent::Oceania),
    ("PR", Continent::NorthAmerica),
    ("PS", Continent::Asia),
    ("PT", Continent::Europe),
    ("PW", Continent::Oceania),
    ("PY", Continent::SouthAmerica),
    ("QA", Continent::Asia),
    ("RE", Continent::Africa),
    ("RO", Continent::Europe),
    ("RS", Continent::Europe),
    ("RU", Continent::Europe),
    ("RW", Continent::Africa),
    ("SA", Continent::Asia),
    ("SB", Continent::Oceania),
    ("SC", Continent::Africa),
    ("SD", Continent::Africa),
    ("SE", Continent::Europe),
    ("SG", Continent::Asia),
    ("SH", Continent::Africa),
    ("SI", Continent::Europe),
    ("SJ", Continent::Europe),
    ("SK", Continent::Europe),
    ("SL", Continent::Africa),
    ("SM", Continent::Europe),
    ("SN", Continent::Africa),
    ("SO", Continent::Africa),
    ("SR", Continent::SouthAmerica),
    ("SS", Continent::Africa),
    ("ST", Continent::Africa),
    ("SV", Continent::NorthAmerica),
    ("SX", Continent::NorthAmerica),
    ("SY", Continent::Asia),
    ("SZ", Continent::Africa),
    ("TC", Continent::NorthAmerica),
    ("TD", Continent::Africa),
    ("TF", Continent::Antarctica),
    ("TG", Continent::Africa),
    ("TH", Continent::Asia),
    ("TJ", Continent::Asia),
    ("TK", Continent::Oceania),
    ("TL", Continent::Oceania),
    ("TM", Continent::Asia),
    ("TN", Continent::Africa),
    ("TO", Continent::Oceania),
    ("TR", Continent::Asia),
    ("TT", Continent::NorthAmerica),
    ("TV", Continent::Oceania),
    ("TW", Continent::Asia),
    ("TZ", Continent::Africa),
    ("UA", Continent::Europe),
    ("UG", Continent::Africa),
    ("UM", Continent::Oceania),
    ("US", Continent::NorthAmerica),
    ("UY", Continent::SouthAmerica),
    ("UZ", Continent::Asia),
    ("VA", Continent::Europe),
    ("VC", Continent::NorthAmerica),
    ("VE", Continent::SouthAmerica),
    ("VG", Continent::NorthAmerica),
    ("VI", Continent::NorthAmerica),
    ("VN", Continent::Asia),
    ("VU", Continent::Oceania),
    ("WF", Continent::Oceania),
    ("WS", Continent::Oceania),
    ("YE", Continent::Asia),
    ("YT", Continent::Africa),
    ("ZA", Continent::Africa),
    ("ZM", Continent::Africa),
    ("ZW", Continent::Africa),
];

pub fn continent(country: &str) -> Option<Continent> {
    COUNTRIES
        .binary_search_by(|(code, _)| (*code).cmp(country))
        .ok()
        .map(|index| COUNTRIES[index].1)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maps_countries_to_continents() {
        assert_eq!(continent("FR"), Some(Continent::Europe));
        assert_eq!(continent("NA"), Some(Continent::Africa));
        assert_eq!(continent("BR"), Some(Continent::SouthAmerica));
        assert_eq!(continent("XX"), None);
        assert!(COUNTRIES.windows(2).all(|w| w[0].0 < w[1].0));
    }
}
