name: Release-plz

on:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: release-plz
  cancel-in-progress: false

jobs:
  release:
    name: Release
    if: github.repository_owner == 'opengeoip'
    runs-on: ubuntu-24.04
    environment: release
    permissions:
      contents: read
    steps:
      - id: token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.BOT_CLIENT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: read
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: rustup toolchain install stable --profile minimal && rustup default stable
      - uses: release-plz/action@b8d6b54b02889ff2ae2bb82e8b57c3a8fc1683a5 # v0.5.139
        with:
          command: release
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}

  pr:
    name: Release pull request
    if: github.repository_owner == 'opengeoip'
    runs-on: ubuntu-24.04
    environment: release
    permissions:
      contents: read
    steps:
      - id: token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ vars.BOT_CLIENT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - run: rustup toolchain install stable --profile minimal && rustup default stable
      - uses: release-plz/action@b8d6b54b02889ff2ae2bb82e8b57c3a8fc1683a5 # v0.5.139
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
